/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    YourContract: {
      address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "productId",
              type: "uint256",
            },
          ],
          name: "CandidateDelisted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "NewCandidate",
          type: "event",
        },
        {
          inputs: [],
          name: "ccount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "clist",
          outputs: [
            {
              internalType: "address",
              name: "_lister",
              type: "address",
            },
            {
              internalType: "string",
              name: "_title",
              type: "string",
            },
            {
              internalType: "string",
              name: "_explanation",
              type: "string",
            },
            {
              internalType: "string",
              name: "_ghub",
              type: "string",
            },
            {
              internalType: "string",
              name: "_ytube",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_vote",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_isdelisted",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "voter",
              type: "address",
            },
          ],
          name: "delegatenewvoter",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cid",
              type: "uint256",
            },
          ],
          name: "delist",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "plister",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "_lister",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "_title",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "_explanation",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "_ghub",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "_ytube",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "_vote",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "_isdelisted",
                  type: "bool",
                },
              ],
              internalType: "struct YourContract.Candidates[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_title",
              type: "string",
            },
            {
              internalType: "string",
              name: "_ghub",
              type: "string",
            },
            {
              internalType: "string",
              name: "_ytube",
              type: "string",
            },
            {
              internalType: "string",
              name: "_explanation",
              type: "string",
            },
          ],
          name: "registerCandidate",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cid",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_vamount",
              type: "uint256",
            },
          ],
          name: "vote",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
